import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { IconAlertTriangle, IconPaperclip, IconRefresh, IconUser } from '@tabler/icons-react'
import { api } from '../services/api.js'

const rows = value => Array.isArray(value) ? value : value && typeof value === 'object' ? Object.values(value) : []
const title = item => item.nombre || item.title || item.tipo || item.descripcion || 'Pendiente operativo'
const relation = item => item.trabajadorId || item.personaId || item.workerId || item.contratoId || item.activoId || item.entityId || item.id
const typeOf = item => { const text=JSON.stringify(item).toLowerCase(); if(/vencid|restring|bloque|no habil|faltante/.test(text))return 'critical'; if(/próxim|proxim|vence/.test(text))return 'upcoming'; return 'operation' }
const category = { critical:['Personas no habilitadas y documentos vencidos','Requieren regularización antes de operar'], upcoming:['Próximos a vencer','Anticípate a renovaciones y vencimientos'], operation:['Alertas de recursos y operación','Pendientes de vehículos, equipos, contratos u órdenes'] }
const groupSummary = items => { const critical=items.filter(item=>typeOf(item)==='critical').length, upcoming=items.filter(item=>typeOf(item)==='upcoming').length, operation=items.filter(item=>typeOf(item)==='operation').length; return [[critical,'crítica'],[upcoming,'próxima'],[operation,'operativa']].filter(([total])=>total).map(([total,label])=>`${total} ${label}${total===1?'':'s'}`).join(' · ') }
const compareGroups = (left,right) => { const critical=item=>item.items.filter(row=>typeOf(row)==='critical').length, upcoming=item=>item.items.filter(row=>typeOf(row)==='upcoming').length; return critical(right)-critical(left)||upcoming(right)-upcoming(left)||right.items.length-left.items.length||left.label.localeCompare(right.label,'es') }

export default function AlertasPage() {
  const navigate=useNavigate(); const [response,setResponse]=useState(null); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('all'); const [open,setOpen]=useState(null)
  const load=async()=>{setLoading(true);try{setResponse(await api.get('/state'))}catch{setStatus('No fue posible cargar las alertas.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const state=response?.state||response||{}; const people=rows(state.trabajadores)
  const groups=useMemo(()=>Object.values([...rows(state.alertas),...rows(state.callouts)].reduce((out,item)=>{const id=relation(item),person=people.find(row=>String(row.id)===String(id)),key=person?`persona-${person.id}`:`registro-${id}`,kind=typeOf(item);out[key] ||= {key,id,label:person?.nombre||item.contratoNombre||item.activoNombre||item.entidad||'Registro sin relación identificada',person,items:[],kinds:new Set()};out[key].items.push(item);out[key].kinds.add(kind);return out},{})).sort(compareGroups),[state,people])
  const counts=useMemo(()=>groups.reduce((out,group)=>{[...group.kinds].forEach(kind=>out[kind]+=group.items.filter(item=>typeOf(item)===kind).length);return out},{critical:0,upcoming:0,operation:0}),[groups])
  const visible=filter==='all'?groups:groups.filter(group=>group.kinds.has(filter))
  const upload=async(event,group)=>{const file=event.target.files?.[0];if(!file)return;setStatus('Cargando evidencia…');try{await api.upload(file,{entityType:'alerta',entityId:String(group.id)});setStatus(`Evidencia adjuntada a ${group.label}.`)}catch(error){setStatus(error.message||'No fue posible adjuntar el archivo.')}finally{event.target.value=''}}
  return <section className="nk-module-page"><header className="nk-module-header"><div><p className="nk-module-kicker">Centro de control</p><h1>Alertas</h1><p>Prioriza pendientes y abre cada persona, recurso o empresa para regularizar todos sus antecedentes.</p></div><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={16}/>Actualizar</button></header>
    <div className="nk-alert-summary">{Object.entries(category).map(([key,[label,copy]])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(filter===key?'all':key)}><b>{loading?'…':counts[key]}</b><span>{label}</span><small>{copy}</small></button>)}</div>{status&&<p className="nk-form-message">{status}</p>}
    <div className="nk-alert-groups">{loading?<div className="nk-module-empty">Cargando alertas…</div>:visible.length?visible.map(group=>{const expanded=open===group.key;return <article className="nk-alert-group" key={group.key}><button className="nk-alert-group-trigger" aria-expanded={expanded} aria-label={`${expanded?'Ocultar':'Mostrar'} ${group.items.length} alertas de ${group.label}`} onClick={()=>setOpen(expanded?null:group.key)}><span><b>{group.label}</b><small>{group.person?`${group.person.rut||'Sin RUT'} · ${group.person.cargo||'Sin cargo'} · ${group.person.proyecto||'Sin orden asignada'}`:'Empresa, contrato, recurso u orden relacionada'}</small></span><span className="nk-alert-toggle-summary">{groupSummary(group.items)}</span><span className="nk-alert-plus" aria-hidden="true">{expanded?'−':'+'}</span></button>{expanded&&<div className="nk-alert-group-detail">{group.person&&<button className="nk-button nk-button-secondary" onClick={()=>navigate(`/app/trabajadores/${group.person.id}`)}><IconUser size={15}/>Ver ficha</button>}<label className="nk-button nk-button-primary"><IconPaperclip size={15}/>Adjuntar evidencia<input type="file" onChange={event=>upload(event,group)} accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" /></label><ul>{group.items.map((item,index)=><li key={item.id||index}><IconAlertTriangle size={16}/><span><b>{title(item)}</b><small>{item.descripcion||item.mensaje||item.estado||'Requiere revisión y regularización.'}</small></span></li>)}</ul></div>}</article>}) : <div className="nk-module-empty"><IconAlertTriangle size={28}/><b>No hay alertas en esta categoría</b><span>Prueba otra vista o actualiza la información.</span></div>}</div>
  </section>
}
