import ModuleWorkspacePage from './ModuleWorkspacePage.jsx'

// Pantallas React declaradas por módulo. Todas usan el espacio común mientras
// se trasladan, una por una, los formularios y reglas del HTML histórico.
const page = key => () => <ModuleWorkspacePage forcedModule={key} />

export const AlertasPage = page('alertas')
export const GestionPersonalProyectoPage = page('gestion-personal-proyecto')
export const CentroOperativoPage = page('centro-operativo')
export const TurnosAsistenciaPage = page('turnos-asistencia')
export const ProteccionEppPage = page('proteccion-epp')
export const FormacionPage = page('formacion')
export const ExamenesPage = page('examenes')
export const SaludOcupacionalPage = page('salud-ocupacional')
export const RestringidosPage = page('restringidos')
export const ComunicacionesPage = page('comunicaciones')
export const VehiculosPage = page('vehiculos')
export const AlojamientosPage = page('alojamientos')
export const CredencialesPage = page('credenciales')
export const TercerosSubcontratosPage = page('terceros-subcontratos')
export const ConveniosPage = page('contratos-convenios')
export const PersonalEmpresaServiciosPage = page('personal-empresa-servicios')
export const HabilitacionesCumplimientoPage = page('habilitaciones-cumplimiento')
export const EvaluacionDesempenoPage = page('evaluacion-desempeno')
export const CumplimientoCorporativoPage = page('cumplimiento-corporativo')
export const HabilitacionClientePage = page('habilitacion-cliente')
export const IncidentesPage = page('incidentes')
export const AuditoriaPage = page('auditoria')
export const ProspectosPage = page('prospectos')
export const ActivosInventarioPage = page('activos-inventario')
export const MaquinariaPage = page('maquinaria')
export const EquiposInstrumentosPage = page('equipos-instrumentos')
export const HerramientasPage = page('herramientas')
export const EppInventarioPage = page('epp-inventario')
export const MaterialesPage = page('materiales')
export const InsumosPage = page('insumos')
export const BodegasPage = page('bodegas')
export const MovimientosInventarioPage = page('movimientos-inventario')
export const MantenimientoPage = page('mantenimiento')
export const AsignacionesPrestamosPage = page('asignaciones-prestamos')
export const ReportesPage = page('reportes')
export const ConfiguracionPage = page('configuracion')
export const ImportarExportarPage = page('importar-exportar')
export const UsuariosPermisosPage = page('usuarios-permisos')
export const BitacoraCambiosPage = page('bitacora')
export const PrivacidadDatosPage = page('privacidad')
export const AdministracionClientesPage = page('administracion-clientes')
