import { useEffect, useMemo, useState } from 'react'
import { IconChartBar, IconRefresh, IconSearch } from '@tabler/icons-react'
import { api } from '../services/api.js'
import '../styles/contractors-secondary.css'

const asRows=value=>Array.isArray(value)?value:[]
const clampRating=value=>{const n=Number(value);return Number.isFinite(n)?Math.max(1,Math.min(5,n)):''}
const scoreOf=row=>{const vals=[row.complianceRating,row.safetyRating,row.serviceRating].map(Number).filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length/5*100):0}
const scoreState=score=>score>=80?{label:'Alto',cls:'nk-badge-ok'}:score>=60?{label:'Aceptable',cls:'nk-badge-warn'}:{label:'Bajo',cls:'nk-badge-error'}

export default function EvaluacionDesempenoPage(){
  const [response,setResponse]=useState(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('todos'),[savingId,setSavingId]=useState(''),[error,setError]=useState('')
  async function load(){setLoading(true);setError('');try{setResponse(await api.get('/state'))}catch(c){setError(c.message||'No fue posible cargar evaluaciones.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const state=response?.state||response||{},versions=response?.moduleVersions||{},companies=asRows(state.subcontratos),canonical=asRows(state.evaluaciones)
  const byCompany=new Map(companies.map(c=>[String(c.id),c]))
  const rows=useMemo(()=>companies.map(company=>{
    const latest=canonical.filter(x=>String(x.subcontratoId||x.terceroId)===String(company.id)).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')))[0]
    return latest?{...latest,company}:{id:`legacy-${company.id}`,subcontratoId:company.id,company,complianceRating:company.complianceRating||'',safetyRating:company.safetyRating||'',serviceRating:company.serviceRating||'',legacy:true}
  }),[companies,canonical])
  const filtered=rows.filter(row=>{const t=query.trim().toLowerCase(),score=scoreOf(row);const band=score>=80?'alto':score>=60?'aceptable':'bajo';return(!t||[row.company?.razon,row.company?.nombre,row.company?.rut].some(v=>String(v||'').toLowerCase().includes(t)))&&(statusFilter==='todos'||band===statusFilter)})
  const summary={companies:rows.length,evaluated:rows.filter(r=>scoreOf(r)>0).length,high:rows.filter(r=>scoreOf(r)>=80).length,low:rows.filter(r=>scoreOf(r)>0&&scoreOf(r)<60).length}
  async function saveRating(row,field,value){const rating=clampRating(value);if(!rating)return;setSavingId(`${row.subcontratoId}-${field}`);setError('');try{const current=asRows(state.evaluaciones),existing=current.find(x=>String(x.subcontratoId||x.terceroId)===String(row.subcontratoId));const base=existing||{id:`eval_${Date.now()}`,subcontratoId:row.subcontratoId,createdAt:new Date().toISOString()};const record={...base,complianceRating:field==='complianceRating'?rating:(existing?.complianceRating||row.complianceRating||''),safetyRating:field==='safetyRating'?rating:(existing?.safetyRating||row.safetyRating||''),serviceRating:field==='serviceRating'?rating:(existing?.serviceRating||row.serviceRating||''),updatedAt:new Date().toISOString()};record.performanceScore=scoreOf(record);const next=existing?current.map(x=>x.id===existing.id?record:x):[...current,record];const result=await api.put('/state/modules',{reason:'Evaluación de contratista actualizada',changes:{evaluaciones:{version:Number(versions.evaluaciones||0),data:next}}});setResponse(r=>({...r,state:{...(r?.state||state),evaluaciones:next},moduleVersions:{...(r?.moduleVersions||versions),...(result?.moduleVersions||{})}}))}catch(c){setError(c.message||'No fue posible guardar la evaluación.')}finally{setSavingId('')}}
  return <div className="nk-contractor-page"><header className="nk-contractor-header"><div><h1>Evaluación de desempeño</h1><p>Evalúa a cada empresa colaboradora en cumplimiento, seguridad y calidad del servicio con una escala de 1 a 5.</p></div><div className="nk-actions"><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={15}/>Actualizar</button></div></header>{error&&<div className="nk-contractor-feedback error">{error}</div>}<section className="nk-contractor-summary"><article><strong>{loading?'…':summary.companies}</strong><span>Empresas</span></article><article><strong>{loading?'…':summary.evaluated}</strong><span>Evaluadas</span></article><article><strong>{loading?'…':summary.high}</strong><span>Desempeño alto</span></article><article><strong>{loading?'…':summary.low}</strong><span>Requieren mejora</span></article></section><section className="nk-card"><div className="nk-contractor-toolbar nk-contractor-toolbar-2"><label className="nk-search"><IconSearch size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa o RUT"/></label><select className="nk-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="todos">Todos los resultados</option><option value="alto">Alto</option><option value="aceptable">Aceptable</option><option value="bajo">Bajo</option></select></div></section><section className="nk-card nk-contractor-table-card">{loading?<div className="nk-empty nk-contractor-empty"><IconChartBar size={30}/><p className="nk-empty-title">Cargando evaluaciones…</p></div>:!filtered.length?<div className="nk-empty nk-contractor-empty"><p className="nk-empty-title">Sin empresas para evaluar</p></div>:<div className="nk-table-wrapper"><table className="nk-table"><thead><tr><th>Empresa externa</th><th>Cumplimiento</th><th>Seguridad</th><th>Calidad / servicio</th><th>Resultado</th></tr></thead><tbody>{filtered.map(row=>{const score=scoreOf(row),st=scoreState(score);return <tr key={row.id}><td><strong>{row.company?.razon||row.company?.nombre}</strong><div className="nk-contractor-subtle">{row.company?.rut||'Sin RUT'}</div></td>{['complianceRating','safetyRating','serviceRating'].map(field=><td key={field}><div className="nk-rating-cell"><input className="nk-input" type="number" min="1" max="5" step="1" defaultValue={row[field]||''} onBlur={e=>saveRating(row,field,e.target.value)} disabled={savingId===`${row.subcontratoId}-${field}`}/><span>/ 5</span></div></td>)}<td><div className="nk-score-result"><strong>{score||0}%</strong><span className={`nk-badge ${st.cls}`}>{score?st.label:'Sin evaluar'}</span></div></td></tr>})}</tbody></table></div>}</section></div>
}
