import { useState } from 'react'
import { Link } from 'react-router-dom'
import { IconMail, IconSend } from '@tabler/icons-react'
import { api } from '../services/api.js'

const input={width:'100%',boxSizing:'border-box',padding:'11px 12px',border:'1px solid #d7d9e2',borderRadius:8,fontSize:14}

export default function ForgotPasswordPage(){
  const [form,setForm]=useState({rut:'',email:''}),[sent,setSent]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(false)
  const submit=async event=>{event.preventDefault();setLoading(true);setMessage('');try{const result=await api.post('/auth/forgot-password',form);setSent(true);setMessage(result.message)}catch{setMessage('No fue posible procesar la solicitud. Intenta nuevamente más tarde.')}finally{setLoading(false)}}
  return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#f6f7fb'}}><section style={{width:'min(420px,100%)',padding:30,border:'1px solid #e0e2ea',borderRadius:10,background:'#fff'}}><IconMail size={28} color="#2a2a8c"/><p style={{margin:'18px 0 5px',color:'#2a2a8c',fontSize:12,fontWeight:800,textTransform:'uppercase'}}>Recuperar acceso</p><h1 style={{margin:'0 0 8px',fontSize:25}}>Restablece tu contraseña</h1><p style={{margin:'0 0 22px',color:'#5d6b7a',fontSize:14,lineHeight:1.5}}>Ingresa el RUT de tu empresa y tu correo autorizado. Te enviaremos un enlace seguro para crear una nueva contraseña.</p>{sent?<div style={{padding:14,borderRadius:8,background:'#eef7f5',color:'#1f5d57',fontSize:14,lineHeight:1.5}}>{message}</div>:<form onSubmit={submit} style={{display:'grid',gap:14}}><label style={{fontSize:12,fontWeight:700}}>RUT de empresa<input required value={form.rut} onChange={event=>setForm({...form,rut:event.target.value})} placeholder="12.345.678-9" style={{...input,marginTop:6}}/></label><label style={{fontSize:12,fontWeight:700}}>Correo personal autorizado<input required type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="persona@empresa.cl" style={{...input,marginTop:6}}/></label>{message&&<p style={{margin:0,color:'#b3261e',fontSize:13}}>{message}</p>}<button disabled={loading} style={{display:'flex',justifyContent:'center',gap:8,padding:'11px',border:0,borderRadius:8,background:'#2a2a8c',color:'#fff',fontWeight:800,cursor:'pointer'}}><IconSend size={16}/>{loading?'Enviando...':'Enviar enlace seguro'}</button></form>}<p style={{margin:'20px 0 0',textAlign:'center',fontSize:13}}><Link to="/login" style={{color:'#00706a',fontWeight:700,textDecoration:'none'}}>Volver al acceso</Link></p></section></main>
}
