import { useEffect, useMemo, useState } from 'react'
import { IconBook, IconSignature as IconFileSignature, IconPlus, IconRefresh, IconX } from '@tabler/icons-react'
import { api } from '../services/api.js'

const list = value => Array.isArray(value) ? value : []
const today = () => new Date().toISOString().slice(0, 10)
const emptyForm = () => ({ mineRef:'', contractRef:'', projectRef:'', bookType:'maestro', bookTitle:'Libro de Obra', entryType:'avance', occurredAt:`${today()}T12:00:00.000Z`, subject:'', body:'', responsible:'', dueAt:'', status:'borrador' })

export default function LibroObraPage() {
  const [entries,setEntries]=useState([]),[state,setState]=useState({}),[form,setForm]=useState(emptyForm),[showForm,setShowForm]=useState(false),[selected,setSelected]=useState(null),[signature,setSignature]=useState({signerName:'',signerEmail:'',signerPhone:'',channel:'email',message:''}),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);try{const [book,appState]=await Promise.all([api.get('/work-books/entries'),api.get('/state')]);setEntries(list(book));setState(appState?.state||appState||{})}catch(error){setNotice(error.message||'No fue posible cargar el Libro de Obra.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const clients=list(state.minas),contracts=list(state.contratos),orders=list(state.mantenciones)
  const summary=useMemo(()=>({total:entries.length,open:entries.filter(row=>!['cerrado','firmado'].includes(row.status)).length,pending:entries.filter(row=>row.signature_state==='pendiente'||row.status==='pendiente_firma').length}),[entries])
  const scopedContracts=contracts.filter(row=>!form.mineRef||String(row.minaId)===String(form.mineRef)); const scopedOrders=orders.filter(row=>!form.mineRef||String(row.minaId)===String(form.mineRef))
  const submit=async event=>{event.preventDefault();setNotice('');try{await api.post('/work-books/entries',{...form,dueAt:form.dueAt||null});setNotice('Anotación registrada con folio correlativo.');setForm(emptyForm());setShowForm(false);await load()}catch(error){setNotice(error.message||'No fue posible registrar la anotación.')}}
  const openEntry=async row=>{try{setSelected(await api.get(`/work-books/entries/${row.id}`));setSignature(current=>({...current,message:`Solicitamos revisar y firmar la anotación ${row.entry_number} del ${row.folio}.`}))}catch(error){setNotice(error.message||'No fue posible abrir la anotación.')}}
  const requestSignature=async event=>{event.preventDefault();if(!selected)return;try{const result=await api.post(`/work-books/entries/${selected.id}/signature-requests`,signature);setNotice(result.delivery_status==='pendiente_configuracion'?'La solicitud quedó registrada. Configure el proveedor de firma, correo o WhatsApp para enviarla.':'Solicitud de firma enviada.');setSelected(await api.get(`/work-books/entries/${selected.id}`))}catch(error){setNotice(error.message||'No fue posible solicitar la firma.')}}
  return <section className="nk-module-page nk-book-page"><header className="nk-module-header"><div><p className="nk-module-kicker">Gestión de proyectos y negocios</p><h1>Libro de Obra</h1><p>Registra instrucciones, acuerdos, avances e incidencias con contexto, evidencia, responsables y firma.</p></div><div className="nk-module-actions"><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={16}/>Actualizar</button><button className="nk-button nk-button-primary" onClick={()=>setShowForm(true)}><IconPlus size={16}/>Nueva anotación</button></div></header>
    <div className="nk-module-summary"><article><b>{summary.total}</b><span>Anotaciones correlativas</span></article><article><b>{summary.open}</b><span>Compromisos abiertos</span></article><article><b>{summary.pending}</b><span>Firmas pendientes</span></article></div>{notice&&<p className="nk-form-message">{notice}</p>}
    <section className="nk-book-list"><header><b>Registro formal</b><span>Una anotación firmada o cerrada conserva su historial y se corrige con una nueva anotación.</span></header>{loading?<p>Cargando anotaciones…</p>:entries.length?entries.map(row=><button key={row.id} onClick={()=>openEntry(row)}><span className="nk-book-folio">{row.folio} · {row.entry_number}</span><span><b>{row.subject}</b><small>{row.book_title} · {row.entry_type.replace('_',' ')} · {String(row.occurred_at).slice(0,10)}</small></span><em className={`nk-book-status ${row.status}`}>{row.status.replace('_',' ')}</em></button>):<p>No hay anotaciones todavía. Crea la primera para iniciar el libro asociado a un cliente y una orden de servicio.</p>}</section>
    {showForm&&<div className="nk-book-modal"><form onSubmit={submit}><header><div><b>Nueva anotación</b><p>El sistema creará o reutilizará el libro asociado al cliente, contrato y orden.</p></div><button type="button" onClick={()=>setShowForm(false)}><IconX size={18}/></button></header><div className="nk-book-form">{[['mineRef','Cliente'],['contractRef','Contrato'],['projectRef','Orden de servicio']].map(([key,label])=><label key={key}>{label}<select required={key!=='contractRef'} value={form[key]} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))}><option value="">Selecciona</option>{(key==='mineRef'?clients:key==='contractRef'?scopedContracts:scopedOrders).map(row=><option value={row.id} key={row.id}>{row.nombre||row.title||row.id}</option>)}</select></label>)}<label>Tipo de libro<select value={form.bookType} onChange={e=>setForm(current=>({...current,bookType:e.target.value}))}>{[['maestro','Maestro'],['seguridad_hsec','Seguridad y salud'],['calidad','Calidad'],['terreno_avance','Terreno y avance'],['comunicaciones','Comunicaciones']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Tipo de anotación<select value={form.entryType} onChange={e=>setForm(current=>({...current,entryType:e.target.value}))}>{['instruccion','consulta','respuesta','avance','incidente','acuerdo','observacion','recepcion','otro'].map(value=><option key={value}>{value}</option>)}</select></label><label>Responsable<input value={form.responsible} onChange={e=>setForm(current=>({...current,responsible:e.target.value}))}/></label><label className="wide">Asunto<input required minLength="3" value={form.subject} onChange={e=>setForm(current=>({...current,subject:e.target.value}))}/></label><label className="wide">Detalle<textarea required minLength="3" value={form.body} onChange={e=>setForm(current=>({...current,body:e.target.value}))}/></label><label>Fecha de compromiso<input type="date" value={form.dueAt} onChange={e=>setForm(current=>({...current,dueAt:e.target.value}))}/></label><label>Estado inicial<select value={form.status} onChange={e=>setForm(current=>({...current,status:e.target.value}))}><option value="borrador">Borrador</option><option value="pendiente_firma">Pendiente de firma</option></select></label></div><footer><button type="button" className="nk-button nk-button-secondary" onClick={()=>setShowForm(false)}>Cancelar</button><button className="nk-button nk-button-primary">Registrar anotación</button></footer></form></div>}
    {selected&&<div className="nk-book-modal"><div className="nk-book-detail"><header><div><b>{selected.folio} · Anotación {selected.entry_number}</b><p>{selected.subject}</p></div><button onClick={()=>setSelected(null)}><IconX size={18}/></button></header><div className="nk-book-detail-body"><p>{selected.body}</p><dl><div><dt>Responsable</dt><dd>{selected.responsible||'Sin asignar'}</dd></div><div><dt>Compromiso</dt><dd>{selected.due_at||'Sin fecha'}</dd></div><div><dt>Estado</dt><dd>{selected.status.replace('_',' ')}</dd></div></dl><section><h2><IconFileSignature size={17}/>Solicitar firma</h2><form className="nk-book-signature" onSubmit={requestSignature}><input required placeholder="Nombre de quien firma" value={signature.signerName} onChange={e=>setSignature(c=>({...c,signerName:e.target.value}))}/><input placeholder="Correo autorizado" type="email" value={signature.signerEmail} onChange={e=>setSignature(c=>({...c,signerEmail:e.target.value}))}/><input placeholder="Teléfono con código país" value={signature.signerPhone} onChange={e=>setSignature(c=>({...c,signerPhone:e.target.value}))}/><select value={signature.channel} onChange={e=>setSignature(c=>({...c,channel:e.target.value}))}><option value="email">Correo</option><option value="whatsapp">WhatsApp</option><option value="ambos">Correo y WhatsApp</option></select><button className="nk-button nk-button-primary">Enviar solicitud</button></form>{list(selected.signature_requests).length>0&&<p className="nk-book-history">Solicitudes: {selected.signature_requests.map(item=>`${item.signer_name} (${item.status})`).join(' · ')}</p>}</section></div></div></div>}
  </section>
}
