import { useEffect, useMemo, useState } from 'react'
import { IconBriefcase, IconChevronDown, IconChevronUp, IconPlus, IconRefresh, IconSearch, IconX } from '@tabler/icons-react'
import { api } from '../services/api.js'
import '../styles/prospectos.css'

const rows = value => Array.isArray(value) ? value : []
const today = () => new Date().toISOString().slice(0, 10)
const STAGES = [['prospecto','Nuevo lead'],['contactada','Contactado'],['reunion','Reunión agendada'],['levantamiento','Levantamiento'],['propuesta','Propuesta enviada'],['negociacion','Negociación'],['ganada','Ganada'],['perdida','Perdida'],['pausa','En pausa']]
const TYPES = [['nuevo_cliente','Nuevo cliente'],['nuevo_contrato','Nuevo contrato'],['nuevo_servicio','Nuevo proyecto / servicio']]
const FOLLOW_TYPES = ['llamada','correo','reunión','whatsapp','propuesta','acuerdo','tarea','observación']
const label=(items,value)=>items.find(([key])=>key===String(value||'').toLowerCase())?.[1]||value||'—'
const company=item=>item.company||item.empresa||item.razon||item.razonSocial||item.name||'Empresa sin nombre'
const contact=item=>item.contact||item.contacto||item.contactName||item.nombreContacto||'Sin contacto'
const amount=item=>Number(item.amount??item.monto??item.value??0)
const probability=item=>Number(item.probability??item.probabilidad??0)
const nextAction=item=>item.nextAction||item.proximaGestion||item.nextActionAt||item.proximaAccion||''
const stageOf=item=>{const stage=String(item.stage||item.etapa||'prospecto').toLowerCase();if(stage==='calificada'||stage==='calificado')return'levantamiento';if(stage==='contactado')return'contactada';return stage}
const isOpen=item=>!['ganada','perdida'].includes(stageOf(item))
const money=(value,currency='CLP')=>{try{return new Intl.NumberFormat('es-CL',{style:'currency',currency:currency||'CLP',maximumFractionDigits:0}).format(Number(value||0))}catch{return`${currency||'CLP'} ${Number(value||0).toLocaleString('es-CL')}`}}
function score(item){let value=0;if(company(item)!=='Empresa sin nombre')value+=8;if(item.rut)value+=8;if(contact(item)!=='Sin contacto')value+=8;if(item.email||item.phone)value+=10;if(item.role||item.cargo)value+=5;if(item.region||item.commune||item.comuna)value+=5;if(item.industry)value+=6;if(item.service||item.servicio||item.need||item.notes)value+=10;if(amount(item)>0)value+=8;if(probability(item)>0)value+=5;if(item.expectedClose||item.cierreEstimado)value+=7;if(nextAction(item))value+=7;if(rows(item.documents).length)value+=7;if(rows(item.followUps).length)value+=7;if(['propuesta','negociacion','ganada'].includes(stageOf(item)))value+=7;return Math.min(100,value)}
function heat(item){const value=score(item);if(stageOf(item)==='ganada')return['Ganada','ok'];if(stageOf(item)==='perdida')return['Perdida','error'];if(nextAction(item)&&nextAction(item)<today()&&isOpen(item))return['Seguimiento vencido','error'];if(value>=80)return['Caliente','ok'];if(value>=50)return['Media','warn'];return['Débil','neutral']}
const empty=()=>({type:'nuevo_cliente',stage:'prospecto',company:'',rut:'',industry:'',source:'',service:'',need:'',contact:'',role:'',email:'',phone:'',amount:'',currency:'CLP',probability:20,expectedClose:'',nextAction:'',owner:'',clientId:'',contractId:'',region:'',commune:'',lossReason:'',notes:'',followUps:[],history:[]})
function normalize(item){return{...empty(),...item,type:item.type||item.tipo||'nuevo_cliente',stage:stageOf(item),company:company(item)==='Empresa sin nombre'?'':company(item),service:item.service||item.servicio||'',need:item.need||item.notes||item.notas||'',contact:contact(item)==='Sin contacto'?'':contact(item),amount:item.amount??item.monto??'',probability:item.probability??item.probabilidad??20,expectedClose:item.expectedClose||item.cierreEstimado||'',nextAction:nextAction(item),owner:item.owner||item.responsable||'',clientId:item.clientId||item.minaId||'',contractId:item.contractId||item.contratoId||'',commune:item.commune||item.comuna||'',lossReason:item.lossReason||'',followUps:rows(item.followUps),history:rows(item.history)}}
async function saveModule(reason,transform){const response=await api.get('/state'),state=response?.state||response||{},version=response?.moduleVersions?.prospectos??0,current=rows(state.prospectos).length?rows(state.prospectos):rows(state.oportunidades);await api.put('/state/modules',{reason,changes:{prospectos:{version,data:transform(current)}}})}

function OpportunityDialog({opportunity,clients,contracts,onClose,onSaved}){
  const[form,setForm]=useState(()=>opportunity?normalize(opportunity):empty()),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const clientContracts=contracts.filter(item=>!form.clientId||String(item.minaId||item.clientId||'')===String(form.clientId))
  async function save(event){event.preventDefault();if(!form.company.trim()||saving)return;setSaving(true);setError('');try{const record={...(opportunity||{}),...form,id:opportunity?.id||`opp_${Date.now()}`,company:form.company.trim(),amount:Number(form.amount||0),probability:Number(form.probability||0),updatedAt:new Date().toISOString(),createdAt:opportunity?.createdAt||new Date().toISOString()};record.score=score(record);await saveModule(opportunity?'Oportunidad comercial actualizada':'Oportunidad comercial registrada',current=>opportunity?current.map(item=>String(item.id)===String(opportunity.id)?record:item):[...current,record]);onSaved()}catch(cause){setError(cause.message||'No fue posible guardar la oportunidad.')}finally{setSaving(false)}}
  return <div className="nk-dialog-backdrop" onMouseDown={onClose}><form className="nk-dialog nk-opportunity-dialog" role="dialog" aria-modal="true" aria-labelledby="nk-opportunity-dialog-title" onSubmit={save} onMouseDown={event=>event.stopPropagation()}>
    <header className="nk-dialog-header"><div><h2 id="nk-opportunity-dialog-title" className="nk-dialog-title">{opportunity?'Editar oportunidad':'Nueva oportunidad'}</h2><p className="nk-opportunity-subtle">Registra primero lo esencial de la oportunidad y completa el seguimiento comercial.</p></div><button className="nk-icon-button" type="button" onClick={onClose} aria-label="Cerrar"><IconX size={18}/></button></header>
    <div className="nk-dialog-body">
      <p className="nk-opportunity-dialog-note">Los campos de Cliente y Contrato son opcionales. La oportunidad puede existir antes de formalizar la relación comercial.</p>
      <section className="nk-opportunity-section nk-opportunity-section-primary"><div className="nk-opportunity-section-header"><div><strong>Oportunidad</strong><span>Información principal para identificar y calificar el negocio.</span></div></div><div className="nk-opportunity-form-grid">
        <label className="nk-field nk-opportunity-wide nk-opportunity-field-emphasis"><span className="nk-label">Empresa</span><input className="nk-input" required autoFocus value={form.company} onChange={event=>setForm({...form,company:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Tipo</span><select className="nk-select" value={form.type} onChange={event=>setForm({...form,type:event.target.value})}>{TYPES.map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
        <label className="nk-field nk-opportunity-field-emphasis"><span className="nk-label">Servicio de interés</span><input className="nk-input" value={form.service} onChange={event=>setForm({...form,service:event.target.value})}/></label>
        <label className="nk-field nk-opportunity-wide nk-opportunity-field-emphasis"><span className="nk-label">Necesidad / dolor detectado</span><textarea className="nk-textarea" rows="2" value={form.need} onChange={event=>setForm({...form,need:event.target.value})}/></label>
      </div></section>
      <section className="nk-opportunity-section"><div className="nk-opportunity-section-header"><div><strong>Contacto</strong><span>Persona con quien se gestiona la oportunidad.</span></div></div><div className="nk-opportunity-form-grid">
        <label className="nk-field"><span className="nk-label">Contacto</span><input className="nk-input" value={form.contact} onChange={event=>setForm({...form,contact:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Cargo</span><input className="nk-input" value={form.role} onChange={event=>setForm({...form,role:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Email</span><input className="nk-input" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Teléfono</span><input className="nk-input" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></label>
      </div></section>
      <section className="nk-opportunity-section"><div className="nk-opportunity-section-header"><div><strong>Gestión comercial</strong><span>Etapa, responsable, valor y próximas acciones del pipeline.</span></div></div><div className="nk-opportunity-form-grid">
        <label className="nk-field"><span className="nk-label">Etapa</span><select className="nk-select" value={form.stage} onChange={event=>setForm({...form,stage:event.target.value})}>{STAGES.map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
        <label className="nk-field"><span className="nk-label">Responsable</span><input className="nk-input" value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}/></label>
        <div className="nk-opportunity-wide nk-opportunity-grid-money">
          <label className="nk-field"><span className="nk-label">Monto</span><input className="nk-input" type="number" min="0" value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label>
          <label className="nk-field"><span className="nk-label">Moneda</span><select className="nk-select" value={form.currency} onChange={event=>setForm({...form,currency:event.target.value})}><option>CLP</option><option>USD</option><option>UF</option></select></label>
          <label className="nk-field"><span className="nk-label">Probabilidad %</span><input className="nk-input" type="number" min="0" max="100" value={form.probability} onChange={event=>setForm({...form,probability:event.target.value})}/></label>
        </div>
        <label className="nk-field"><span className="nk-label">Cierre estimado</span><input className="nk-input" type="date" value={form.expectedClose} onChange={event=>setForm({...form,expectedClose:event.target.value})}/></label>
        <label className="nk-field nk-opportunity-field-emphasis"><span className="nk-label">Próxima gestión</span><input className="nk-input" type="date" value={form.nextAction} onChange={event=>setForm({...form,nextAction:event.target.value})}/></label>
        {form.stage==='perdida'&&<label className="nk-field nk-opportunity-wide"><span className="nk-label">Motivo de pérdida</span><input className="nk-input" value={form.lossReason} onChange={event=>setForm({...form,lossReason:event.target.value})}/></label>}
      </div></section>
      <section className="nk-opportunity-section nk-opportunity-section-secondary"><div className="nk-opportunity-section-header"><div><strong>Información adicional</strong><span>Contexto de segmentación, ubicación y vínculos existentes.</span></div></div><div className="nk-opportunity-form-grid">
        <label className="nk-field"><span className="nk-label">RUT</span><input className="nk-input" value={form.rut} onChange={event=>setForm({...form,rut:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Industria</span><input className="nk-input" value={form.industry} onChange={event=>setForm({...form,industry:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Origen</span><input className="nk-input" value={form.source} onChange={event=>setForm({...form,source:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Región</span><input className="nk-input" value={form.region} onChange={event=>setForm({...form,region:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Comuna</span><input className="nk-input" value={form.commune} onChange={event=>setForm({...form,commune:event.target.value})}/></label>
        <label className="nk-field"><span className="nk-label">Cliente existente</span><select className="nk-select" value={form.clientId} onChange={event=>setForm({...form,clientId:event.target.value,contractId:''})}><option value="">Sin cliente asociado</option>{clients.map(item=><option key={item.id} value={item.id}>{item.razon||item.nombre||item.name||item.id}</option>)}</select></label>
        <label className="nk-field"><span className="nk-label">Contrato existente</span><select className="nk-select" value={form.contractId} onChange={event=>setForm({...form,contractId:event.target.value})}><option value="">Sin contrato asociado</option>{clientContracts.map(item=><option key={item.id} value={item.id}>{item.codigo||item.numero||item.nombre||item.id}</option>)}</select></label>
        <label className="nk-field nk-opportunity-wide"><span className="nk-label">Notas</span><textarea className="nk-textarea" rows="3" value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label>
      </div></section>
      {error&&<p className="nk-form-error">{error}</p>}
    </div>
    <footer className="nk-dialog-footer"><button className="nk-button nk-button-secondary" type="button" onClick={onClose}>Cancelar</button><button className="nk-button nk-button-primary" disabled={saving}>{saving?'Guardando…':'Guardar oportunidad'}</button></footer>
  </form></div>
}

function FollowDialog({opportunity,onClose,onSaved}){
  const[type,setType]=useState('llamada'),[detail,setDetail]=useState(''),[date,setDate]=useState(today()),[owner,setOwner]=useState(opportunity.owner||''),[saving,setSaving]=useState(false)
  async function save(event){event.preventDefault();if(!detail.trim()||saving)return;setSaving(true);try{const entry={id:`of_${Date.now()}`,type,date,detail:detail.trim(),owner:owner.trim(),at:new Date().toISOString()};await saveModule('Gestión comercial registrada',current=>current.map(item=>String(item.id)===String(opportunity.id)?{...item,followUps:[entry,...rows(item.followUps)],updatedAt:new Date().toISOString()}:item));onSaved()}finally{setSaving(false)}}
  return <div className="nk-dialog-backdrop" onMouseDown={onClose}><form className="nk-dialog nk-follow-dialog" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><header className="nk-dialog-header"><div><h2 className="nk-dialog-title">Bitácora · {company(opportunity)}</h2><p className="nk-opportunity-subtle">Seguimiento comercial de la oportunidad.</p></div><button className="nk-icon-button" type="button" onClick={onClose}><IconX size={18}/></button></header><div className="nk-dialog-body"><div className="nk-opportunity-form-grid"><label className="nk-field"><span className="nk-label">Tipo de gestión</span><select className="nk-select" value={type} onChange={event=>setType(event.target.value)}>{FOLLOW_TYPES.map(value=><option key={value}>{value}</option>)}</select></label><label className="nk-field"><span className="nk-label">Fecha</span><input className="nk-input" type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="nk-field nk-opportunity-wide"><span className="nk-label">Detalle</span><textarea className="nk-textarea" required rows="3" value={detail} onChange={event=>setDetail(event.target.value)}/></label><label className="nk-field"><span className="nk-label">Responsable</span><input className="nk-input" value={owner} onChange={event=>setOwner(event.target.value)}/></label></div><div className="nk-follow-list">{rows(opportunity.followUps).map(item=><div key={item.id||item.at}><strong>{item.type||'gestión'} · {item.date||String(item.at||'').slice(0,10)}</strong><span>{item.detail}</span><small>{item.owner||''}</small></div>)}{!rows(opportunity.followUps).length&&<p className="nk-opportunity-subtle">Sin gestiones registradas.</p>}</div></div><footer className="nk-dialog-footer"><button className="nk-button nk-button-secondary" type="button" onClick={onClose}>Cerrar</button><button className="nk-button nk-button-primary" disabled={saving}>Registrar gestión</button></footer></form></div>
}

export default function ProspectosPage(){
  const[response,setResponse]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[typeFilter,setTypeFilter]=useState('todos'),[stageFilter,setStageFilter]=useState('todos'),[industryFilter,setIndustryFilter]=useState(''),[heatFilter,setHeatFilter]=useState(''),[regionFilter,setRegionFilter]=useState(''),[communeFilter,setCommuneFilter]=useState(''),[more,setMore]=useState(false),[editing,setEditing]=useState(null),[following,setFollowing]=useState(null)
  async function load(){setLoading(true);setError('');try{setResponse(await api.get('/state'))}catch(cause){setError(cause.message||'No fue posible cargar oportunidades.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const state=response?.state||response||{},canonical=rows(state.prospectos),opportunities=(canonical.length?canonical:rows(state.oportunidades)).map(normalize),clients=rows(state.minas).length?rows(state.minas):rows(state.clientes),contracts=rows(state.contratos)
  const unique=mapper=>[...new Set(opportunities.map(mapper).filter(Boolean))].sort(),industries=unique(item=>item.industry),regions=unique(item=>item.region),communes=unique(item=>item.commune||item.comuna)
  const filtered=useMemo(()=>{const text=query.trim().toLowerCase();return opportunities.filter(item=>{const temperature=heat(item)[0];return(!text||[company(item),contact(item),item.service,item.need,item.rut,item.owner].some(value=>String(value||'').toLowerCase().includes(text)))&&(typeFilter==='todos'||item.type===typeFilter)&&(stageFilter==='todos'||stageOf(item)===stageFilter)&&(!industryFilter||item.industry===industryFilter)&&(!regionFilter||item.region===regionFilter)&&(!communeFilter||(item.commune||item.comuna)===communeFilter)&&(!heatFilter||(heatFilter==='hot'?temperature==='Caliente':heatFilter==='medium'?temperature==='Media':heatFilter==='weak'?temperature==='Débil':temperature==='Seguimiento vencido'))})},[opportunities,query,typeFilter,stageFilter,industryFilter,heatFilter,regionFilter,communeFilter])
  const summary=filtered.reduce((acc,item)=>{acc.total++;if(isOpen(item)){acc.gross+=amount(item);acc.weighted+=amount(item)*probability(item)/100;if(nextAction(item)&&nextAction(item)<today())acc.overdue++}if(heat(item)[0]==='Caliente')acc.hot++;return acc},{total:0,gross:0,weighted:0,overdue:0,hot:0})
  async function advance(item){const index=STAGES.findIndex(([key])=>key===stageOf(item)),next=STAGES[Math.min(5,Math.max(0,index+1))]?.[0]||'contactada',at=new Date().toISOString(),entry={id:`of_${Date.now()}`,type:'cambio_etapa',date:today(),detail:`Etapa cambiada de ${label(STAGES,stageOf(item))} a ${label(STAGES,next)}`,owner:item.owner||'',at};await saveModule('Etapa comercial actualizada',current=>current.map(row=>String(row.id)===String(item.id)?{...row,stage:next,score:score({...row,stage:next}),history:[...rows(row.history),{at,action:'cambio_etapa',from:stageOf(item),to:next}],followUps:[entry,...rows(row.followUps)],updatedAt:at}:row));load()}
  return <div className="nk-opportunity-page">
    <header className="nk-opportunity-header"><div><h1>Prospectos y oportunidades</h1><p>Gestiona el embudo comercial, score, seguimiento y próxima acción antes de convertir una oportunidad.</p></div><div className="nk-actions"><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={15}/>Actualizar</button><button className="nk-button nk-button-primary" onClick={()=>setEditing({})}><IconPlus size={15}/>Nueva oportunidad</button></div></header>
    {error&&<div className="nk-opportunity-feedback error">{error}</div>}
    <section className="nk-card nk-opportunity-filter-card"><div className="nk-opportunity-toolbar"><label className="nk-search"><IconSearch size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar empresa, contacto o servicio"/></label><select className="nk-select" value={typeFilter} onChange={event=>setTypeFilter(event.target.value)}><option value="todos">Todos los tipos</option>{TYPES.map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><select className="nk-select" value={stageFilter} onChange={event=>setStageFilter(event.target.value)}><option value="todos">Todas las etapas</option>{STAGES.map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><button className="nk-button nk-button-secondary" type="button" onClick={()=>setMore(value=>!value)}>Más filtros {more?<IconChevronUp size={14}/>:<IconChevronDown size={14}/>}</button></div>{more&&<div className="nk-opportunity-more-filters"><select className="nk-select" value={industryFilter} onChange={event=>setIndustryFilter(event.target.value)}><option value="">Todas las industrias</option>{industries.map(value=><option key={value}>{value}</option>)}</select><select className="nk-select" value={heatFilter} onChange={event=>setHeatFilter(event.target.value)}><option value="">Toda temperatura</option><option value="hot">Calientes</option><option value="medium">Media</option><option value="weak">Débil</option><option value="late">Seguimiento vencido</option></select><select className="nk-select" value={regionFilter} onChange={event=>setRegionFilter(event.target.value)}><option value="">Todas las regiones</option>{regions.map(value=><option key={value}>{value}</option>)}</select><select className="nk-select" value={communeFilter} onChange={event=>setCommuneFilter(event.target.value)}><option value="">Todas las comunas</option>{communes.map(value=><option key={value}>{value}</option>)}</select></div>}</section>
    <section className="nk-opportunity-summary"><article><strong>{loading?'…':summary.total}</strong><span>Oportunidades</span></article><article><strong>{loading?'…':money(summary.gross)}</strong><span>Pipeline bruto</span></article><article><strong>{loading?'…':money(summary.weighted)}</strong><span>Pipeline ponderado</span></article><article><strong>{loading?'…':summary.hot}</strong><span>Calientes</span></article><article><strong>{loading?'…':summary.overdue}</strong><span>Gestiones vencidas</span></article></section>
    {!loading&&<section className="nk-card nk-kanban-card"><div className="nk-kanban-head"><div><strong>Embudo comercial visual</strong><span>Prioriza oportunidades por score y próxima gestión.</span></div></div><div className="nk-kanban">{STAGES.filter(([key])=>key!=='pausa').map(([key,value])=>{const list=filtered.filter(item=>stageOf(item)===key);return <div className="nk-kanban-column" key={key}><header><strong>{value}</strong><span>{list.length}</span></header><small>{money(list.reduce((total,item)=>total+amount(item),0))}</small>{list.slice(0,8).map(item=>{const temperature=heat(item);return <article key={item.id}><strong>{company(item)}</strong><p>{item.service||item.need||'Sin necesidad'}</p><div><span className={`nk-heat nk-heat-${temperature[1]}`}>{temperature[0]}</span><span>{score(item)}/100</span></div><small>Próx: {nextAction(item)||'sin fecha'}</small><footer><button type="button" onClick={()=>setFollowing(item)}>Bitácora</button>{isOpen(item)&&stageOf(item)!=='pausa'&&<button type="button" onClick={()=>advance(item)}>Avanzar</button>}</footer></article>})}{!list.length&&<p className="nk-opportunity-subtle">Sin oportunidades</p>}</div>})}</div></section>}
    <section className="nk-card nk-opportunity-table-card">{loading?<div className="nk-empty"><IconBriefcase size={30}/><p className="nk-empty-title">Cargando oportunidades…</p></div>:!filtered.length?<div className="nk-empty"><p className="nk-empty-title">Sin oportunidades para mostrar</p></div>:<div className="nk-table-wrapper"><table className="nk-table nk-opportunity-table"><thead><tr><th>Empresa / oportunidad</th><th>Industria</th><th>Tipo</th><th>Contacto</th><th>Etapa / score</th><th>Monto / prob.</th><th>Próxima gestión</th><th>Seguimiento</th><th>Acciones</th></tr></thead><tbody>{filtered.map(item=>{const temperature=heat(item);return <tr key={item.id}><td><strong>{company(item)}</strong><div className="nk-opportunity-subtle">{item.service||item.need||'Sin necesidad definida'}</div></td><td>{item.industry||'—'}<div className="nk-opportunity-subtle">{item.source||'Sin origen'}</div></td><td>{label(TYPES,item.type)}</td><td>{contact(item)}<div className="nk-opportunity-subtle">{item.role||item.email||'—'}</div></td><td><span className={`nk-heat nk-heat-${temperature[1]}`}>{temperature[0]}</span><div className="nk-opportunity-subtle">{label(STAGES,stageOf(item))} · {score(item)}/100</div></td><td><strong>{money(amount(item),item.currency)}</strong><div className="nk-opportunity-subtle">{probability(item)}%</div></td><td className={nextAction(item)&&nextAction(item)<today()&&isOpen(item)?'nk-opportunity-overdue':''}>{nextAction(item)||'Sin fecha'}</td><td>{item.owner||'Sin responsable'}<div className="nk-opportunity-subtle">{rows(item.followUps).length} gestiones</div></td><td><div className="nk-row-actions"><button className="nk-button nk-button-secondary nk-button-small" type="button" onClick={()=>setFollowing(item)}>Bitácora</button><button className="nk-button nk-button-secondary nk-button-small" type="button" onClick={()=>setEditing(item)}>Abrir</button></div></td></tr>})}</tbody></table></div>}</section>
    {editing!==null&&<OpportunityDialog opportunity={editing.id?editing:null} clients={clients} contracts={contracts} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load()}}/>}
    {following&&<FollowDialog opportunity={following} onClose={()=>setFollowing(null)} onSaved={()=>{setFollowing(null);load()}}/>}
  </div>
}
