import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { IconDownload, IconRefresh, IconUpload } from '@tabler/icons-react'
import { api } from '../services/api.js'

const families=[['trabajadores','Reportes trabajadores',['trabajadores','turnos','asistencias','eppDeliveries','cursos','examenes','protocolosSalud','credenciales']],['comercial','Reportes clientes, contratos y proyectos',['minas','contratos','mantenciones','oportunidades','workBookEntries']],['operacion','Reportes operación y servicios',['alojamientos','comunicaciones','incidentes','permisosTrabajo']],['ejecutivos','Reportes ejecutivos',['minas','contratos','mantenciones','oportunidades','workBookEntries','comunicaciones']],['flota','Reportes flota y maquinaria',['vehiculos','activos','inventoryItems','inventoryMovements','mantenimiento','assignments','bodegas']],['auditoria','Reportes auditoría y cumplimiento',['empresaDocs','acreditacionesMandante','auditorias','documentos','incidentes','protocolosSalud']],['contratistas','Reportes contratistas',['subcontratos','convenios','personalContratista','habilitaciones','evaluaciones']]]
const labels={trabajadores:'Personas',turnos:'Turnos',asistencias:'Asistencia',eppDeliveries:'Entregas de EPP',cursos:'Formación',examenes:'Exámenes',protocolosSalud:'Salud ocupacional',credenciales:'Credenciales',minas:'Clientes',contratos:'Contratos',mantenciones:'Órdenes de servicio',oportunidades:'Prospectos y oportunidades',vehiculos:'Flota y equipos móviles',hoteles:'Alojamientos',alojamientos:'Estadías',comunicaciones:'Comunicaciones',incidentes:'Incidentes',permisosTrabajo:'Permisos de trabajo',subcontratos:'Terceros y subcontratos',convenios:'Convenios',personalContratista:'Personas de empresas colaboradoras',habilitaciones:'Habilitaciones',evaluaciones:'Evaluaciones',inventoryItems:'Existencias',activos:'Activos',inventoryMovements:'Movimientos',mantenimiento:'Mantenimiento',assignments:'Asignaciones y préstamos',bodegas:'Bodegas',empresaDocs:'Documentación corporativa',acreditacionesMandante:'Requisitos del cliente',auditorias:'Auditorías',documentos:'Documentos',workBookEntries:'Libro de Obra'}
const rows=value=>Array.isArray(value)?value:value&&typeof value==='object'?Object.values(value):[]
const csvEscape=value=>`"${String(value??'').replaceAll('"','""')}"`

export default function ReportesPage(){const navigate=useNavigate();const [state,setState]=useState({}),[family,setFamily]=useState('trabajadores'),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const result=await api.get('/state');setState(result?.state||result||{})}catch(error){setNotice(error.message||'No fue posible cargar la información.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const selected=families.find(item=>item[0]===family)||families[0];const collections=useMemo(()=>selected[2].map(key=>[key,rows(state[key])]),[selected,state]);const download=()=>{const lines=['Familia,Módulo,Registro'];collections.forEach(([key,items])=>items.forEach(row=>lines.push([selected[1],labels[key],row.nombre||row.title||row.descripcion||row.id].map(csvEscape).join(','))));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}));link.download=`nexo-klar-${family}-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);setNotice('Reporte descargado en formato CSV.')} ;return <section className="nk-module-page nk-reports-page"><header className="nk-module-header"><div><p className="nk-module-kicker">Reportes y datos</p><h1>Reportes y analítica</h1><p>Consulta y descarga la información por familia funcional, sin mezclar datos de procesos distintos.</p></div><div className="nk-module-actions"><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={16}/>Actualizar</button><button className="nk-button nk-button-secondary" onClick={()=>navigate('/app/importar-exportar')}><IconUpload size={16}/>Importar y exportar</button><button className="nk-button nk-button-primary" onClick={download}><IconDownload size={16}/>Descargar reporte</button></div></header>{notice&&<p className="nk-form-message">{notice}</p>}<div className="nk-report-families">{families.map(([id,name,keys])=><button className={id===family?'active':''} key={id} onClick={()=>setFamily(id)}><b>{name}</b><span>{keys.reduce((total,key)=>total+rows(state[key]).length,0)} registros</span></button>)}</div><section className="nk-report-workspace"><header><div><h2>{selected[1]}</h2><p>Elige un reporte agrupado por módulo y descarga solo la información de esta familia.</p></div></header>{loading?<p>Cargando datos…</p>:<div className="nk-report-grid">{collections.map(([key,items])=><article key={key}><b>{labels[key]}</b><strong>{items.length}</strong><span>{items.slice(0,3).map(row=>row.nombre||row.title||row.descripcion||row.id).filter(Boolean).join(' · ')||'Sin registros'}</span></article>)}</div>}</section></section>}
