import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { IconHeartRateMonitor, IconPlus, IconRefresh, IconSearch, IconX } from '@tabler/icons-react'
import { api } from '../services/api.js'
import '../styles/people-compliance.css'

const statusFor=item=>{const raw=String(item.estado||'').toLowerCase();if(/cerrad|finalizad|resuelt/.test(raw))return{label:'Vigente',cls:'nk-badge-ok',key:'ok'};if(/alert|pendiente|restric|seguimiento/.test(raw))return{label:'Requiere revisión',cls:'nk-badge-warn',key:'warn'};return{label:item.estado||'Sin información',cls:'nk-badge-none',key:'none'}}

function HealthDialog({workers,onClose,onSaved}){
 const [form,setForm]=useState({workerId:'',protocolo:'',riesgo:'',estado:'seguimiento',responsable:'',notes:''});const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 async function save(e){e.preventDefault();if(!form.workerId||!form.protocolo.trim())return;setSaving(true);setError('');try{const r=await api.get('/state');const s=r?.state||r||{};const version=r?.moduleVersions?.protocolosSalud??0;const worker=(s.trabajadores||[]).find(w=>w.id===form.workerId);if(!worker)throw new Error('La persona ya no está disponible.');const item={id:`salud_${Date.now()}`,workerId:worker.id,persona:worker.nombre,protocolo:form.protocolo.trim(),riesgo:form.riesgo.trim(),estado:form.estado,responsable:form.responsable.trim(),notes:form.notes.trim(),createdAt:new Date().toISOString()};await api.put('/state/modules',{reason:`Protocolo de salud registrado para ${worker.nombre}`,changes:{protocolosSalud:{version,data:[...(s.protocolosSalud||[]),item]}}});onSaved()}catch(c){setError(c.message||'No fue posible guardar el protocolo.')}finally{setSaving(false)}}
 return <div className="nk-dialog-backdrop" role="presentation" onMouseDown={onClose}><form className="nk-dialog" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><header className="nk-dialog-header"><div><h2 className="nk-dialog-title">Gestionar protocolo</h2><p className="nk-compliance-subtle">Registra seguimiento ocupacional asociado a una persona.</p></div><button className="nk-icon-button" type="button" onClick={onClose} aria-label="Cerrar"><IconX size={18}/></button></header><div className="nk-dialog-body"><div className="nk-compliance-dialog-grid"><div className="nk-field nk-compliance-dialog-wide"><label className="nk-label">Persona</label><select className="nk-select" required value={form.workerId} onChange={e=>setForm({...form,workerId:e.target.value})}><option value="">Seleccionar persona</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre} · {w.rut||'Sin RUT'}</option>)}</select></div><div className="nk-field nk-compliance-dialog-wide"><label className="nk-label">Protocolo / seguimiento</label><input className="nk-input" required value={form.protocolo} onChange={e=>setForm({...form,protocolo:e.target.value})} placeholder="Ej.: Vigilancia por exposición a ruido"/></div><div className="nk-field"><label className="nk-label">Riesgo / exposición</label><input className="nk-input" value={form.riesgo} onChange={e=>setForm({...form,riesgo:e.target.value})}/></div><div className="nk-field"><label className="nk-label">Estado</label><select className="nk-select" value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option value="seguimiento">En seguimiento</option><option value="pendiente">Pendiente</option><option value="cerrado">Cerrado</option></select></div><div className="nk-field"><label className="nk-label">Responsable</label><input className="nk-input" value={form.responsable} onChange={e=>setForm({...form,responsable:e.target.value})}/></div><div className="nk-field"><label className="nk-label">Observaciones</label><input className="nk-input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div>{error&&<p className="nk-form-error">{error}</p>}</div><footer className="nk-dialog-footer"><button className="nk-button nk-button-secondary" type="button" onClick={onClose}>Cancelar</button><button className="nk-button nk-button-primary" disabled={saving}>{saving?'Guardando…':'Guardar protocolo'}</button></footer></form></div>
}

export default function SaludOcupacionalPage(){
 const navigate=useNavigate();const [response,setResponse]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [creating,setCreating]=useState(false);const [query,setQuery]=useState('');const [statusFilter,setStatusFilter]=useState('todos')
 async function load(){setLoading(true);setError('');try{setResponse(await api.get('/state'))}catch(c){setError(c.message||'No fue posible cargar salud ocupacional.')}finally{setLoading(false)}} useEffect(()=>{load()},[])
 const state=response?.state||response||{};const workers=state.trabajadores||[];const records=useMemo(()=> (state.protocolosSalud||[]).map(i=>{const wid=i.workerId||i.trabId||i.personaId;const w=workers.find(x=>x.id===wid);return{...i,workerId:wid,workerName:w?.nombre||i.persona||'Persona no identificada',workerRut:w?.rut||i.rut||'',workerRole:w?.cargo||w?.especialidad||'',protocolo:i.protocolo||i.nombre||i.title||'Seguimiento ocupacional'}}),[state.protocolosSalud,workers])
 const filtered=useMemo(()=>{const t=query.toLowerCase().trim();return records.filter(i=>{const st=statusFor(i);return(!t||[i.workerName,i.workerRut,i.workerRole,i.protocolo,i.riesgo,i.responsable].some(v=>String(v||'').toLowerCase().includes(t)))&&(statusFilter==='todos'||st.key===statusFilter)})},[records,query,statusFilter])
 const summary=useMemo(()=>records.reduce((a,i)=>{a.total++;const k=statusFor(i).key;if(k==='ok')a.ok++;if(k==='warn')a.warn++;if(k==='none')a.none++;return a},{total:0,ok:0,warn:0,none:0}),[records])
 return <div className="nk-compliance-page"><header className="nk-compliance-header"><div><h1>Salud Ocupacional</h1><p>Gestiona protocolos y seguimientos asociados a exposición, riesgo y cargo, sin mezclar esta vista con los exámenes de aptitud.</p></div><div className="nk-actions"><button className="nk-button nk-button-secondary" onClick={load}><IconRefresh size={15}/>Actualizar</button><button className="nk-button nk-button-primary" onClick={()=>setCreating(true)} disabled={!workers.length}><IconPlus size={15}/>Gestionar protocolo</button></div></header>{error&&<div className="nk-compliance-feedback error"><span>{error}</span></div>}<section className="nk-compliance-summary"><article className="nk-compliance-kpi"><strong>{loading?'…':summary.total}</strong><span>Protocolos registrados</span></article><article className="nk-compliance-kpi"><strong>{loading?'…':summary.ok}</strong><span>Cerrados</span></article><article className="nk-compliance-kpi"><strong>{loading?'…':summary.warn}</strong><span>En revisión</span></article><article className="nk-compliance-kpi"><strong>{loading?'…':summary.none}</strong><span>Sin clasificación</span></article></section><section className="nk-card"><div className="nk-compliance-toolbar"><label className="nk-search"><IconSearch size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar persona, protocolo o riesgo"/></label><div className="nk-field"><label className="nk-label">Estado</label><select className="nk-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="todos">Todos</option><option value="warn">Requiere revisión</option><option value="ok">Cerrado</option><option value="none">Sin información</option></select></div></div></section><section className="nk-card">{loading?<div className="nk-empty nk-compliance-empty"><IconHeartRateMonitor size={30}/><p className="nk-empty-title">Cargando salud ocupacional…</p></div>:filtered.length===0?<div className="nk-empty nk-compliance-empty"><IconHeartRateMonitor size={30}/><p className="nk-empty-title">Sin registros para mostrar</p></div>:<div className="nk-table-wrapper"><table className="nk-table"><thead><tr><th>Persona</th><th>Protocolo</th><th>Riesgo / exposición</th><th>Responsable</th><th>Estado</th><th/></tr></thead><tbody>{filtered.map((i,idx)=>{const st=statusFor(i);return <tr key={i.id||idx}><td><div className="nk-compliance-person"><strong>{i.workerName}</strong><span>{i.workerRut||'Sin RUT'} · {i.workerRole||'Sin cargo'}</span></div></td><td>{i.protocolo}</td><td>{i.riesgo||'—'}</td><td>{i.responsable||'—'}</td><td><span className={`nk-badge ${st.cls}`}>{st.label}</span></td><td>{i.workerId&&<button className="nk-button nk-button-quiet" onClick={()=>navigate(`/app/trabajadores/${i.workerId}`)}>Ver ficha</button>}</td></tr>})}</tbody></table></div>}</section>{creating&&<HealthDialog workers={workers} onClose={()=>setCreating(false)} onSaved={()=>{setCreating(false);load()}}/>}</div>
}
