import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { IconCheck, IconPlus, IconRefresh, IconSearch } from '@tabler/icons-react'
import { api } from '../services/api.js'
import { useAuth } from '../services/auth.jsx'
import '../styles/vehiculos.css'

const rows=value=>Array.isArray(value)?value:[]
const newId=()=>globalThis.crypto?.randomUUID?.()||`vehiculo-${Date.now()}-${Math.random().toString(16).slice(2)}`
const editors=new Set(['domian_admin','client_admin','prevencion'])
const emptyDraft=()=>({tipo:'vehiculo',nombre:'',patente:'',serie:'',marca:'',modelo:'',estado:'disponible',propiedad:'propia',arriendoVence:'',operadorId:'',minaIds:[],mantId:'',observacion:''})
const normalize=value=>String(value||'').trim().toLowerCase().replace(/\s+/g,' ')
const plate=value=>normalize(value).replace(/[^a-z0-9]/g,'')
const labelFor=item=>item.nombre||[item.marca,item.modelo].filter(Boolean).join(' ')||item.patente||item.serie||'Recurso móvil'
const statusLabel=value=>({disponible:'Disponible',asignado:'Asignado',mantenimiento:'Mantenimiento',fuera_servicio:'Fuera de servicio'}[value]||String(value||'Disponible').replaceAll('_',' '))

export default function VehiculosPage(){
 const {session}=useAuth();const canEdit=editors.has(session?.user?.role)
 const [response,setResponse]=useState(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [selectedId,setSelectedId]=useState(null);const [creating,setCreating]=useState(false);const [draft,setDraft]=useState(emptyDraft);const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState('');const [clientFilter,setClientFilter]=useState('');const [message,setMessage]=useState('');const [messageTone,setMessageTone]=useState('')
 async function load(){setLoading(true);setMessage('');try{setResponse(await api.get('/state'))}catch{setMessage('No fue posible cargar la flota.');setMessageTone('error')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const state=response?.state||response||{}
 const vehicles=useMemo(()=>rows(state.vehiculos),[state.vehiculos])
 const workers=useMemo(()=>rows(state.trabajadores),[state.trabajadores])
 const clients=useMemo(()=>{const canonical=rows(state.minas);return canonical.length||state.minas?canonical:rows(state.clientes)},[state.minas,state.clientes])
 const orders=useMemo(()=>{const canonical=rows(state.mantenciones);return canonical.length||state.mantenciones?canonical:rows(state.proyectos)},[state.mantenciones,state.proyectos])
 const workerById=useMemo(()=>new Map(workers.map(x=>[String(x.id),x])),[workers])
 const clientById=useMemo(()=>new Map(clients.map(x=>[String(x.id),x])),[clients])
 const orderById=useMemo(()=>new Map(orders.map(x=>[String(x.id),x])),[orders])
 const visible=useMemo(()=>{const term=normalize(search);return vehicles.filter(item=>{if(statusFilter&&String(item.estado||item.status||'disponible')!==statusFilter)return false;if(clientFilter&&!rows(item.minaIds).some(id=>String(id)===String(clientFilter)))return false;if(!term)return true;const operator=workerById.get(String(item.operadorId));const order=orderById.get(String(item.mantId||item.proyectoId||item.ordenId||item.orderId));const mines=rows(item.minaIds).map(id=>clientById.get(String(id))?.nombre).filter(Boolean);return[item.nombre,item.patente,item.serie,item.marca,item.modelo,item.tipo,item.propiedad,operator?.nombre,order?.nombre,order?.codigo,...mines].filter(Boolean).some(v=>normalize(v).includes(term))})},[vehicles,search,statusFilter,clientFilter,workerById,orderById,clientById])
 const selected=vehicles.find(x=>String(x.id)===String(selectedId))||null
 const available=vehicles.filter(x=>normalize(x.estado||x.status||'disponible')==='disponible').length
 const assigned=vehicles.filter(x=>normalize(x.estado||x.status)==='asignado').length
 const maintenance=vehicles.filter(x=>['mantenimiento','fuera_servicio'].includes(normalize(x.estado||x.status))).length
 useEffect(()=>{if(creating)return;if(!selectedId){setDraft(emptyDraft());return}const current=vehicles.find(x=>String(x.id)===String(selectedId));if(!current){setSelectedId(null);setDraft(emptyDraft());return}setDraft({...emptyDraft(),...current,minaIds:rows(current.minaIds),mantId:current.mantId||current.proyectoId||current.ordenId||current.orderId||'',arriendoVence:current.arriendoVence||current.arriendoFin||current.arrendadoHasta||''})},[vehicles,selectedId,creating])
 const update=key=>event=>setDraft(current=>({...current,[key]:event.target.value}))
 const updateMulti=key=>event=>setDraft(current=>({...current,[key]:Array.from(event.target.selectedOptions).map(option=>option.value)}))
 const openResource=item=>{setCreating(false);setSelectedId(item.id);setDraft({...emptyDraft(),...item,minaIds:rows(item.minaIds),mantId:item.mantId||item.proyectoId||item.ordenId||item.orderId||'',arriendoVence:item.arriendoVence||item.arriendoFin||item.arrendadoHasta||''});setMessage('')}
 async function save(event){event.preventDefault();if(!canEdit)return;if(!draft.nombre.trim()&&!draft.patente.trim()&&!draft.serie.trim()){setMessage('Indica un nombre, patente o número de serie.');setMessageTone('error');return}if(normalize(draft.propiedad)==='arrendada'&&!draft.arriendoVence){setMessage('Indica la fecha de término del arriendo.');setMessageTone('error');return}const duplicate=vehicles.find(item=>String(item.id)!==String(selectedId)&&((draft.patente&&item.patente&&plate(item.patente)===plate(draft.patente))||(draft.serie&&item.serie&&normalize(item.serie)===normalize(draft.serie))));if(duplicate){setMessage('Ya existe un recurso con la misma patente o número de serie.');setMessageTone('error');return}setSaving(true);setMessage('');try{const id=creating?(draft.id||newId()):selectedId;const now=new Date().toISOString();const saved={...draft,id,nombre:draft.nombre.trim(),patente:draft.patente.trim(),serie:draft.serie.trim(),marca:draft.marca.trim(),modelo:draft.modelo.trim(),observacion:draft.observacion.trim(),minaIds:rows(draft.minaIds),operadorId:draft.operadorId||'',mantId:draft.mantId||'',arriendoVence:normalize(draft.propiedad)==='arrendada'?draft.arriendoVence:'',updatedAt:now,...(creating?{createdAt:draft.createdAt||now}:{})};delete saved.proyectoId;delete saved.ordenId;delete saved.orderId;delete saved.arriendoFin;delete saved.arrendadoHasta;const next=creating?[...vehicles,saved]:vehicles.map(x=>String(x.id)===String(id)?saved:x);const result=await api.put('/state/modules',{changes:{vehiculos:{version:Number(response?.moduleVersions?.vehiculos||0),data:next}},reason:creating?'Recurso móvil creado':'Recurso móvil actualizado'});setResponse(current=>({...(current||{}),state:{...(current?.state||current||{}),vehiculos:next},moduleVersions:{...(current?.moduleVersions||{}),...result.moduleVersions}}));setSelectedId(id);setCreating(false);setDraft(saved);setMessage(creating?'Recurso registrado.':'Cambios guardados con trazabilidad.');setMessageTone('ok')}catch(error){setMessage(error.message||'No fue posible guardar el recurso.');setMessageTone('error')}finally{setSaving(false)}}
 const selectedOrder=orderById.get(String(draft.mantId||''));const selectedOperator=workerById.get(String(draft.operadorId||''));const selectedClients=rows(draft.minaIds).map(id=>clientById.get(String(id))).filter(Boolean)
 return <section className="nk-fleet-page">
  <header className="nk-fleet-header"><div><h1>Flota y equipos móviles</h1><p>Administra disponibilidad, responsables y relación de vehículos y equipos móviles con la operación.</p></div><div className="nk-actions"><button className="nk-button nk-button-secondary" type="button" onClick={load} disabled={loading}><IconRefresh size={16}/>Actualizar</button>{canEdit&&<button className="nk-button nk-button-primary" type="button" onClick={()=>{setCreating(true);setSelectedId(null);setDraft({...emptyDraft(),id:newId()});setMessage('')}}><IconPlus size={16}/>Registrar recurso</button>}</div></header>
  {message&&<div className={`nk-fleet-feedback ${messageTone}`}>{message}</div>}
  <section className="nk-fleet-filters nk-card"><label className="nk-search"><IconSearch size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Patente, serie, equipo, operador..." aria-label="Buscar recursos móviles"/></label><select className="nk-select" value={clientFilter} onChange={e=>setClientFilter(e.target.value)} aria-label="Filtrar por cliente o faena"><option value="">Todos los clientes / faenas</option>{clients.map(client=><option key={client.id} value={client.id}>{client.nombre||client.mandante||client.id}</option>)}</select><select className="nk-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} aria-label="Filtrar por disponibilidad"><option value="">Todos los estados</option><option value="disponible">Disponible</option><option value="asignado">Asignado</option><option value="mantenimiento">Mantenimiento</option><option value="fuera_servicio">Fuera de servicio</option></select></section>
  <section className="nk-fleet-summary"><article><b>{vehicles.length}</b><span>Total</span></article><article><b>{available}</b><span>Disponibles</span></article><article><b>{assigned}</b><span>Asignados</span></article><article><b>{maintenance}</b><span>Mantenimiento / fuera de servicio</span></article></section>
  <section className="nk-card nk-fleet-table-card"><div className="nk-fleet-table-head"><div><strong>Vehículos y equipos</strong><span>{visible.length} de {vehicles.length} registros</span></div></div>{loading?<div className="nk-fleet-empty">Cargando…</div>:!visible.length?<div className="nk-fleet-empty">No hay recursos para mostrar.</div>:<div className="nk-table-wrapper"><table className="nk-table nk-fleet-table"><thead><tr><th>Equipo</th><th>Cliente / faena</th><th>Responsable</th><th>Orden de servicio</th><th>Propiedad</th><th>Estado</th><th></th></tr></thead><tbody>{visible.map(item=>{const operator=workerById.get(String(item.operadorId));const order=orderById.get(String(item.mantId||item.proyectoId||item.ordenId||item.orderId||''));const itemClients=rows(item.minaIds).map(id=>clientById.get(String(id))).filter(Boolean);return <tr key={item.id}><td><strong>{labelFor(item)}</strong><small>{item.tipo||'vehículo'} · {item.patente||item.serie||'Sin identificador'}</small></td><td>{itemClients.length?itemClients.map((client,index)=><span key={client.id}>{index>0?<br/>:null}<Link className="nk-context-link" to={`/app/clientes/${encodeURIComponent(client.id)}`}>{client.nombre||client.mandante||client.id}</Link></span>):'—'}</td><td>{operator?<Link className="nk-context-link" to={`/app/trabajadores/${encodeURIComponent(operator.id)}`}>{operator.nombre||operator.rut||operator.id}</Link>:'—'}</td><td>{order?<Link className="nk-context-link" to={`/app/servicios/${encodeURIComponent(order.id)}`}>{order.codigo||order.nombre||order.id}</Link>:'—'}</td><td>{normalize(item.propiedad)==='arrendada'?<>Arrendada{item.arriendoVence||item.arriendoFin||item.arrendadoHasta?<small>Hasta {item.arriendoVence||item.arriendoFin||item.arrendadoHasta}</small>:null}</>:'Propia'}</td><td><span className="nk-badge nk-badge-none">{statusLabel(item.estado||item.status||'disponible')}</span></td><td><button className="nk-button nk-button-secondary" type="button" onClick={()=>openResource(item)}>Abrir ficha</button></td></tr>})}</tbody></table></div>}</section>
  {(creating||selected)&&<form className="nk-fleet-workspace nk-card" onSubmit={save}><div className="nk-fleet-workspace-head"><div><p className="nk-fleet-kicker">{creating?'Nuevo recurso':'Ficha del recurso'}</p><h2>{creating?'Registrar recurso':labelFor(draft)}</h2><p>Datos operacionales, responsable y relaciones del recurso.</p></div><div className="nk-actions">{!creating&&<button className="nk-button nk-button-quiet" type="button" onClick={()=>{setSelectedId(null);setDraft(emptyDraft());setMessage('')}}>Cerrar ficha</button>}{canEdit&&<button className="nk-button nk-button-primary" type="submit" disabled={saving}><IconCheck size={16}/>{saving?'Guardando…':'Guardar cambios'}</button>}</div></div><div className="nk-fleet-form-grid">
      <label className="nk-field"><span className="nk-label">Tipo</span><select className="nk-select" disabled={!canEdit} value={draft.tipo} onChange={update('tipo')}><option value="vehiculo">Vehículo</option><option value="equipo_movil">Equipo móvil</option></select></label><label className="nk-field"><span className="nk-label">Estado operacional</span><select className="nk-select" disabled={!canEdit} value={draft.estado} onChange={update('estado')}><option value="disponible">Disponible</option><option value="asignado">Asignado</option><option value="mantenimiento">Mantenimiento</option><option value="fuera_servicio">Fuera de servicio</option></select></label>
      <label className="nk-field nk-fleet-wide"><span className="nk-label">Nombre / identificación interna</span><input className="nk-input" disabled={!canEdit} value={draft.nombre} onChange={update('nombre')} placeholder="Camioneta operaciones 01"/></label><label className="nk-field"><span className="nk-label">Patente</span><input className="nk-input" disabled={!canEdit} value={draft.patente} onChange={update('patente')} placeholder="ABCD12"/></label><label className="nk-field"><span className="nk-label">N.º de serie / VIN</span><input className="nk-input" disabled={!canEdit} value={draft.serie} onChange={update('serie')} placeholder="Serie o VIN"/></label><label className="nk-field"><span className="nk-label">Marca</span><input className="nk-input" disabled={!canEdit} value={draft.marca} onChange={update('marca')}/></label><label className="nk-field"><span className="nk-label">Modelo</span><input className="nk-input" disabled={!canEdit} value={draft.modelo} onChange={update('modelo')}/></label><label className="nk-field"><span className="nk-label">Propiedad</span><select className="nk-select" disabled={!canEdit} value={draft.propiedad} onChange={update('propiedad')}><option value="propia">Propia</option><option value="arrendada">Arrendada</option></select></label>{draft.propiedad==='arrendada'&&<label className="nk-field"><span className="nk-label">Término de arriendo</span><input className="nk-input" type="date" disabled={!canEdit} value={draft.arriendoVence} onChange={update('arriendoVence')}/></label>}
      <label className="nk-field"><span className="nk-label">Operador responsable</span><select className="nk-select" disabled={!canEdit} value={draft.operadorId} onChange={update('operadorId')}><option value="">Sin operador asignado</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.nombre||worker.rut||worker.id}</option>)}</select></label><label className="nk-field"><span className="nk-label">Orden de servicio actual</span><select className="nk-select" disabled={!canEdit} value={draft.mantId} onChange={update('mantId')}><option value="">Sin orden asociada</option>{orders.map(order=><option key={order.id} value={order.id}>{order.codigo?`${order.codigo} · `:''}{order.nombre||order.id}</option>)}</select></label><label className="nk-field nk-fleet-wide"><span className="nk-label">Clientes / faenas habilitadas</span><select className="nk-select nk-fleet-multi" multiple disabled={!canEdit} value={rows(draft.minaIds)} onChange={updateMulti('minaIds')}>{clients.map(client=><option key={client.id} value={client.id}>{client.nombre||client.mandante||client.id}</option>)}</select><small className="nk-fleet-help">Puedes seleccionar más de una opción.</small></label><label className="nk-field nk-fleet-wide"><span className="nk-label">Observación</span><textarea className="nk-textarea" rows="4" disabled={!canEdit} value={draft.observacion} onChange={update('observacion')} placeholder="Antecedentes operacionales del recurso."/></label>
     </div><section className="nk-fleet-context"><strong>Contexto operacional</strong><span>Operador: {selectedOperator?<Link className="nk-context-link" to={`/app/trabajadores/${encodeURIComponent(selectedOperator.id)}`}>{selectedOperator.nombre||selectedOperator.rut||selectedOperator.id}</Link>:'Sin operador asignado'}</span><span>Clientes/faenas: {selectedClients.length?selectedClients.map((client,index)=><span key={client.id}>{index>0?', ':''}<Link className="nk-context-link" to={`/app/clientes/${encodeURIComponent(client.id)}`}>{client.nombre||client.mandante||client.id}</Link></span>):'Sin asociación'}</span>{selectedOrder?<span>Orden: <Link className="nk-context-link" to={`/app/servicios/${encodeURIComponent(selectedOrder.id)}`}>{selectedOrder.codigo?`${selectedOrder.codigo} · `:''}{selectedOrder.nombre||selectedOrder.id}</Link></span>:<span>Orden: Sin orden asociada</span>}</section></form>}
 </section>
}
